# Generated by Django 4.2.8 on 2024-01-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='post_images/% Y/% m/% d/'),
        ),
    ]
