# Generated by Django 4.2.8 on 2024-02-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_accounts_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('technology', 'technology'), ('programming language', 'programing language'), ('Artificial intelligence', 'Artificial intelligence'), ('other', 'other')], default='other', max_length=50),
        ),
    ]
